version: '3.8'

services:
  map-service:
    build:
      context: .
      network: host
    container_name: map-microservice
    ports:
      - "8002:8000"
    env_file:
      - .env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

  # Nginx для демо-страницы
  demo:
    build:
      context: .
      dockerfile: Dockerfile.nginx
      network: host
    container_name: map-demo
    ports:
      - "8080:80"
    depends_on:
      - map-service
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge