FROM nginx:alpine
# Удаляем дефолтный конфиг Nginx
RUN rm /etc/nginx/conf.d/default.conf
# Копируем наш конфиг и html-страницу
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY demo.html /usr/share/nginx/html/demo.html