FROM nginx:stable-alpine

# Копируем ВСЕ html файлы (и index.html, и demo.html) в папку, откуда их раздает Nginx
COPY *.html /usr/share/nginx/html/

# Либо, если копируете поштучно:
# COPY index.html /usr/share/nginx/html/index.html
# COPY demo.html /usr/share/nginx/html/demo.html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]