server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index demo.html;

    location / {
        try_files $uri $uri/ /demo.html;
    }

    location /api/ {
        proxy_pass http://map-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}